# MySQL ??
server:
  address: localhost
  port: 8080
  servlet:
      session:
        tracking-modes: cookie

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: > # '>' : ??? ??, line 10 : DB ??, line 11 : DB ??? ?? DB ?? 
      jdbc:mysql://localhost:3306/oneshot?
      createDatabaseIfNotExist=true
      &userUnicode=true
      &characterEncoding=UTF-8
      &characterSetResults=UTF-8
      &useSSL=false
      &serverTimezone=Asia/Seoul
    username: root # DB ????
    password: 1111 # DB ???? ????
  devtools:
    restart:
      enabled: false
  thymeleaf:
    cache: false



